[prepare-release v1.0.12-rc]

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -145,6 +145,10 @@ jobs:
           if [[ $commit_message =~ \[prepare-release\ v([0-9]+\.[0-9]+\.[0-9]+-rc)\] ]]; then
             version=${BASH_REMATCH[1]}
             git tag -a "$version" -m "Version $version"
+          else
+            echo "Invalid commit message format"
+            exit 1
+          fi
 
       - name: Push tag
         run: git push origin v${{ steps.extract_version.outputs.version }}
